---
- name: Deploy Flask App
  hosts: f
  become: yes
  remote_user: root
  
  tasks:
    - name: update apt
      apt:
        update_cache: yes
      become: yes
        
    - name: Ensure Python and necessary packages are installed
      apt:
        name:
          - python3-pip
          - python3-dev
          - build-essential
          - python3-venv
          - python3-flask
          - git
        state: present
      become: yes
        
    - name: install ansible
      pip:
        name: ansible
        state: present
        
    - name: create directry for virtual environment
      command: mkdir -p /opt/project2-1
      
    - name: create virtual environment
      command: python3 -m venv /opt/project2-1/venv
      become: yes
      
    - name: activate virtual environment
      command: /bin/bash -c "source /opt/project2-1/venv/bin/activate"
      become: yes
      
    - name: copy flask app file
      copy:
        src: app.py
        dest: /opt/project2-1/app.py
        
    - name: Install Flask dependencies
      pip:
        name: flask
        executable: /opt/project2-1/venv/bin/pip
        state: present

     # when: "'inactive' in ufw_status.stdout"
     # ignore_errors: yes #ignore errors if it has already been enables
      
    - name: Ensure incoming traffic on port
      ufw:
        rule: allow
        proto: tcp
        port: 5000
        comment: "allow incoming traffic to flask app"
      become: yes

    - name: Ensure incoming traffic on port
      ufw:
        rule: allow
        proto: tcp
        port: 22
      become: yes

    #- name: allow port
     # command: ufw allow 22

    #- name: allow port
     # command: ufw allow 5000 

    #- name: enable ufw
     # command: ufw --force enable
        
    - name: start ufw as a service
      systemd:
        name: ufw
        state: restarted
      become: yes

    #- name: reload ufw
     # command: ufw reload

    #- name: change to flask app directory
     # command: python3 /opt/project2-1/app.py &
      #become: yes

    - name: activate virtual env
      command: /bin/bash -c "source /opt/project2-1/venv/bin/activate"

    - name: set flask app environment variable
      command: /bin/bash -c "export FLASK_APP=/opt/project2-1/app.py"

    - name: run flask app
      command: flask run --host=0.0.0.0 --port=5000
      async: 0
      poll: 0
   # - name: activate the virtual environment and Start Flask app development server
    #  command: /bin/bash -c "source /opt/project2-1/venv/bin/activate && export FLASK_APP=/opt/project2-1/app.py && opt/project2-1/venv/bin/flask run --host=0.0.0.0 &"
     # async: 0
      #poll: 0
...
