---
- name: Deploy Flask App
  hosts: f
  become: yes  # Run tasks with elevated privileges
  remote_user: root

  tasks:
    - name: update yum
      ansible.builtin.yum:
        name: '*'
        state: latest
        
    - name: Ensure Python and necessary packages are installed
      yum:
        name: 
          - python3-pip
          - python3-devel
          - gcc
          - make
          - automake
          - autoconf
          - kernel-devel
          - patch
          - libffi-devel
          - openssl-devel
          - git
        state: present

    - name: create python environment
      pip: 
        name: virtualenv
        state: present

    - name: create virtual environment
      command: mkdir -p /opt/project2-1 && virtualenv /opt/project2-1/env

    - name: activate virtual environment
      command: /bin/bash -c "source /opt/project2-1/env/env/activate"

    - name: Install Flask dependencies
      pip:
        name: flask # You can add Gunicorn as a production-ready WSGI server 
        executable: /opt/project2-1/env/bin/pip
        state: present

    - name: Copy Flask app files
      copy:
        src: /home/ec2-user/flacks-app/app.py   #/path/to/your/app
        dest: /opt/project2-1/app.py

    - name: allow traffic on port 5000
      ufw:
        rule: allow
        proto: tcp
        port: 5000

    - name: restart  ufw
      systemd:
        name: ufw
        state: restarted

    - name: activate the virtual environment and Start Flask app development server
      command: /bin/bash -c "source /opt/project2-1/env/bin/activate && export FLASK_APP=/opt/project2-1/app.py && opt/project2-1/env/binflask run -- host-0.0.0.0 &"
      async: 0
      poll: 0

...
