---
- name: Deploy Flask App
  hosts: f
  become: yes
  remote_user: root
  
  tasks:
    - name: update apt
      apt:
        update_cache: yes
        
    - name: Ensure Python and necessary packages are installed
      apt:
        name:
          - python3-pip
          - python3-dev
          - build-essential
          - python3-venv
          - git
        state: present
        
    - name: install ansible
      pip:
        name: ansible
        state: present
        
    - name: create directry for virtual environment
      command: mkdir -p /opt/project2-1
      
    - name: create virtual environment
      become: yes
      command: python3 -m venv /opt/project2-1/venv
      
    - name: activate virtual environment
      command: /bin/bash -c "source /opt/project2-1/venv/bin/activate"
      
    - name: copy flask app file
      copy:
        src: app.py
        dest: /opt/project2-1/app.py
        
    - name: Install Flask dependencies
      pip:
        name: flask
        executable: /opt/project2-1/venv/bin/pip
        state: present

     # when: "'inactive' in ufw_status.stdout"
     # ignore_errors: yes #ignore errors if it has already been enables
      
    - name: Ensure incoming traffic on port
      ufw:
        rule: allow
        proto: tcp
        port: 5000
        comment: "allow incoming traffic to flask app"

    - name: Ensure incoming traffic on port
      ufw:
        rule: allow
        proto: tcp
        port: 22

    - name: enable ufw
      command: ufw --force enable
        
    #- name: start flask web app as a service
     # systemd:
     #   name: ufw
      #  state: restarted

    - name: reload ufw
      command: ufw reload
        
    - name: activate the virtual environment and Start Flask app development server
      command: /bin/bash -c "source /opt/project2-1/venv/bin/activate && export FLASK_APP=/opt/project2-1/app.py && opt/project2-1/venv/bin/flask run --host=0.0.0.0 --port=5000 #&"
      async: 0
      poll: 0
...
