---
- name: Deploy Flask App
  hosts: f
  become: yes  # Run tasks with elevated privileges
  remote_user: root

  tasks:
    - name: update yum
      ansible.builtin.yum:
        name: '*'
        state: latest
        
    - name: Ensure Python and necessary packages are installed
      yum:
        name: 
          - python3
          - python3-pip
          - python3-devel
          - gcc
          - make
          - automake
          - autoconf
          - kernel-devel
          - patch
          - libffi-devel
          - openssl-devel
          - git
          - firewalld
        state: present
        
    - name: install ansible
      pip:
        name: ansible
        state: present

    - name: create python environment
      pip: 
        name: virtualenv
        state: present

    - name: create directry for virtual environment
      command: mkdir -p /opt/project2-1 
      
    - name: create virtual environment
      become: yes
      command: python3 -m venv /opt/project2-1/venv

    - name: activate virtual environment
      command: /bin/bash -c "source /opt/project2-1/venv/bin/activate"

    - name: Install Flask dependencies
      pip:
        name: flask # You can add Gunicorn as a production-ready WSGI server 
        executable: /opt/project2-1/venv/bin/pip
        state: present

    - name: Copy Flask app files
      copy:
        src: /home/ec2-user/flacks-app/app.py   #/path/to/your/app
        dest: /opt/project2-1/app.py

    - name: Ensure firewalld is started and enabled
      become: yes
      service:
        name: firewalld
        state: started
        enabled: yes

    - name: allow traffic on port 5000
      firewalld_zone:
        zone: public
        port: 5000/tcp
        permanent: yes
        state: enabled
    #  when: firewalld.check_mode == false

    - name: restart  firewalld
      service:
        name: firewalld
        state: reloaded
    #  when: firewalld.check_mode == false

    - name: activate the virtual environment and Start Flask app development server
      command: /bin/bash -c "source /opt/project2-1/venv/bin/activate && export FLASK_APP=/opt/project2-1/app.py && opt/project2-1/venv/binflask run -- host-0.0.0.0 &"
      async: 0
      poll: 0

...
