---
- name: Deploy Flask App
  hosts: 172.31.31.71
  become: yes  # Run tasks with elevated privileges

  tasks:
    - name: Ensure Python is installed
      become: yes
      package:
        name: python3
        state: present

    - name: Install Flask dependencies
      pip:
        name: "{{ item }}"
      loop:
        - flask
        - gunicorn  # You can use Gunicorn as a production-ready WSGI server

    - name: Copy Flask app files
      copy:
        src: /path/to/your/app
        dest: /path/on/remote/server

    - name: Start Flask app with Gunicorn
      command: gunicorn -w 4 -b 0.0.0.0:5000 your_app_module:app
      args:
        chdir: /path/on/remote/server

...